### ISSUE TITLE
Additional transition phase in between animate in/out

### ISSUE THREAD

**Issue by axelra82** [IanLunn/Sequence#181]
Would love to see option to have animation pass in between animation-in/animation-out.

So motion can continue, but in slower rate before animating out.

Example:

animate-in .title1
left: 25%
transition: all 1s ease-in-out

animate-tween .title1
left: 5%
transition: all 4s ease-in

animate-out .title1
left: 115%
transition: all 1s ease-in-out

This way the motion keeps going while the delay keeps ticking for the next animation switch. A breaking point if you will.

PS. This is my first post to GitHub, so pleas forgive me if I've posted in wrong category or something. Not really sure how GitHub work yet  :) DS

**Comment by IanLunn** [comment]
This is possible in v2. There is no additional phase but v2 doesn't have the requirement of certain elements animating anymore so you can set an element to animate infinitely and tell Sequence.js to ignore it so autoPlay can continue counting.
