### ISSUE TITLE
Preload on moble?

### ISSUE THREAD

**Issue by Beetlecat** [IanLunn/Sequence#184]
Any reason that the preloader would not fire in a moble scenario? I've set it to pre-load all frames and images, and it takes quite a while to load the first frame, but I never see the circles. Is there a way to force the preload cycle to loop so I can verify position, etc.?

-- thank you for this excellent project!

**Comment by IanLunn** [comment]
Will close this as all efforts are now going into v2. We've added a `pausePreloader` option to make the preloader stick on during styling and debugging.
