### ISSUE TITLE
Conflict with wookmark pinterestgallery plugins

### ISSUE THREAD

**Issue by anbwar** [IanLunn/Sequence#252]
Hello everyone,
When i used sequencejs with pinterest gallery plugin the animation of tiles dont work, and there is no issue on console js.
does someone  have the same issue ?,
i note that sequencejs works fine , but the problem is with pinterestgallery on hover block

Thank you for your help

**Comment by IanLunn** [comment]
Do you have a link to the project? I am unfamiliar with pinterest gallery.

**Comment by anbwar** [comment]
sorry @IanLunn  it's a desktop version , just the on mouse hover animation of pinterestgallery wookmark tiles doesent work fine after adding the sequencejs slider

**Comment by IanLunn** [comment]
Sorry, can't do much without a link.

**Comment by anbwar** [comment]
@IanLunn  i have told you that there are no js issues on browser console
