### ISSUE TITLE
100% Width of steps is not really 100%

### ISSUE THREAD

**Issue by VeeK727** [IanLunn/Sequence#275]
Hi, I'm having trouble with 100% width of the step `<li>` tags. I've added the property `width: 100%;` but on mobile screen the `<li>` is like 96% the width of the screen. It only covers the screen if I increase the width to 104% at least. There's no margin or padding anywhere, can some one take a look at this demo and find out the cause?

[Demo](http://bwdmedia.in/testbench/webdev/)

Use Keyboard to change slides

**Comment by IanLunn** [comment]
Looks like you got this answered on [StackOverflow](http://stackoverflow.com/questions/33330391/sequencejs-width-of-step-is-not-100?utm_source=dlvr.it&utm_medium=twitter) so will close the issue.
